# $XDG_CONFIG_HOME/k9s/plugin.yml
plugin:
  fred:
    # Define a mnemonic to invoke the plugin
    shortCut: Shift-D
    # What will be shown on the K9s menu
    description: Use Debug Container
    # Collections of views that support this shortcut. (You can use `all`)
    scopes:
      - pod
    # The command to run upon invocation. Can use Krew plugins here too!
    command: kubectl
    # Whether or not to run the command in background mode
    background: false
    # Defines the command arguments
    args:
      - debug
      - -it
      - --image=ghcr.io/japan4415/discords-debug-container:main
      - $NAME
      - -n
      - $NAMESPACE
      - --
      - bash
